---
title: "compare weather staions - MRC"
output: html_document
date: "2025-04-07"
---

```{r prep_weather, fig.width=10, fig.height=6, echo = FALSE, message=FALSE, warning=FALSE}
# Load libraries
library(readxl)
library(dplyr)
library(lubridate)
library(plotly)
library(readr)
library(ecmwfr)


# Set file paths (change if necessary)
setwd("C:/Users/user01/Downloads")
file_mrc <- "CR1000_mrc_FifteenMinute.xlsx"
file_meter <- "MRC_weather(z6-28104)-Configuration 1-1744054176.082678.csv"
sat <- "reanalysis-era5-single-levels-timeseries-sfcyulyozwu.csv"

# Read data from Excel
df_mrc <- read_excel(file_mrc, skip = 1)  # skip metadata rows
df_mrc <- df_mrc %>% slice(-1, -2)
df_meter <- read_csv(file_meter, skip = 2)
df_sat <- as.data.frame(read_csv(sat))

# Clean CR1000 data
df_mrc <- df_mrc %>%
  rename_with(~ gsub(" ", "_", .x)) %>%
  mutate(TIMESTAMP = ymd_hms(TIMESTAMP)) %>%
  select(
    TIMESTAMP,
    Temp = AirTC_1_Avg,
    Temp2 = AirTC_2_Avg,
    RH = RH_1,
    RH2 = RH_2,
    Solar = Solar1_kW_Avg,
    Solar2 = Solar2_kW_Avg,
    WindSpeed = WS_mph_S_WVT,
    WindDir = WindDir_D1_WVT,
    Rain = Rain_mm_Tot
  )

df_mrc <- df_mrc %>%
  mutate(
    Temp = as.numeric(Temp),
    Temp2 = as.numeric(Temp2),
    RH = as.numeric(RH),
    RH2 = as.numeric(RH2),
    Solar = as.numeric(Solar) * 1000,
    Solar2 = as.numeric(Solar2) * 1000,
    WindSpeed = as.numeric(WindSpeed) * 0.44704, 
    WindDir = as.numeric(WindDir), 
    Rain = as.numeric(Rain) 
  )


# Clean MRC weather data

df_meter <- df_meter %>%
  rename_with(~ gsub(" ", "_", .x)) %>%
  mutate(Timestamps = dmy_hms(Timestamps),
         es1 = 0.611 * exp((17.502 * `°C_RH_Sensor_Temp`) / (`°C_RH_Sensor_Temp` + 240.97)), #°C_Air_Temperature
         es2 = 0.611 * exp((17.502 * `°C_Air_Temperature`) / (`°C_Air_Temperature` + 240.97)), #°C_Air_Temperature
         RH1 = (`kPa_Vapor_Pressure` / es1) * 100,
         RH2 = (`kPa_Vapor_Pressure` / es2) * 100
    
  ) %>%
  select(
    Timestamps,
    MinTemp = `°C_Min_Air_Temperature`, # °C_Air_Temperature
    Temp = `°C_Air_Temperature`, # °C_Air_Temperature
    MaxTemp = `°C_Max_Air_Temperature`, # °C_Air_Temperature
    Solar = `W/m²_Solar_Radiation`,
    WindSpeed = `m/s_Wind_Speed`,
    WindDir = `°_Wind_Direction`,
    Rain = mm_Precipitation, 
    RH1 = RH1,
    RH2 = RH2
  ) 



# Assuming df_meter is your data frame
df_meter_15min <- df_meter %>%
  mutate(Timestamps = floor_date(Timestamps, "15 minutes")) %>%
  group_by(Timestamps) %>%
  summarise(
    Temp = mean(Temp, na.rm = TRUE),
    MinTemp = min(MinTemp, na.rm = TRUE),
    MaxTemp = max(MaxTemp, na.rm = TRUE),
    Solar = mean(Solar, na.rm = TRUE),
    WindSpeed = mean(WindSpeed, na.rm = TRUE),
    WindDir = mean(WindDir, na.rm = TRUE),
    Rain = sum(Rain, na.rm = TRUE),
    RH1 = mean(RH1, na.rm = TRUE),
    RH2 = mean(RH2, na.rm = TRUE)
  )

# Function to calculate wind speed and direction
calculate_wind <- function(u, v) {
  speed <- sqrt(u^2 + v^2)
  direction <- atan2(-u, -v) * (180 / pi)
  direction <- (direction + 360) %% 360 # Ensure the direction is between 0 and 360
  return(list(speed = speed, direction = direction))
}

# Apply the function to each row
wind_data <- lapply(1:nrow(df_sat), function(i) {
  u <- df_sat$u10[i]
  v <- df_sat$v10[i]
  calculate_wind(u, v)
})

# Add results to the data frame
df_sat$wind_speed <- sapply(wind_data, function(x) x$speed)
df_sat$wind_direction <- sapply(wind_data, function(x) x$direction)
df_sat$temp <- df_sat$t2m - 273.15
df_sat$rain <- df_sat$tp * 60 *15 
```



```{r vis_weather, fig.width=10, fig.height=6, echo = FALSE, message=FALSE, warning=FALSE}
####
# Define station names as character variables
station_1 <- "MRC"
station_2 <- "METER"
station_2 <- "SAT"

#Rain
plot_ly() %>%
  add_lines(data = df_meter_15min, x = ~Timestamps, y = ~Rain, name = "METER", line = list(color = "darkblue")) %>%
  add_lines(data = df_mrc, x = ~TIMESTAMP, y = ~Rain, name = "MRC", line = list(color = "darkred")) %>%
  add_lines(data = df_sat, x = ~valid_time, y = ~rain, name = "SAT", line = list(color = "purple")) %>%
  layout(yaxis = list(title = "Rainfall (mm)"))

#RH (Relative Humidity)
plot_ly() %>%
  add_lines(data = df_meter_15min, x = ~Timestamps, y = ~RH1, name = "METER sens", line = list(color = "lightblue")) %>%
  add_lines(data = df_meter_15min, x = ~Timestamps, y = ~RH2, name = "METER air", line = list(color = "darkblue")) %>%
  add_lines(data = df_mrc, x = ~TIMESTAMP, y = ~RH, name = "MRC1", line = list(color = "red")) %>%
  add_lines(data = df_mrc, x = ~TIMESTAMP, y = ~RH2, name = "MRC2", line = list(color = "darkred")) %>%
  layout(yaxis = list(title = "Relative Humidity %"))

#Temp (Temperature)
plot_ly() %>%
  add_lines(data = df_meter_15min, x = ~Timestamps, y = ~MaxTemp, name = "max METER", line = list(color = "darkblue")) %>%
  add_lines(data = df_meter_15min, x = ~Timestamps, y = ~Temp, name = "mean METER", line = list(color = "blue")) %>%
  add_lines(data = df_meter_15min, x = ~Timestamps, y = ~MinTemp, name = "min METER", line = list(color = "lightblue")) %>%
  add_lines(data = df_mrc, x = ~TIMESTAMP, y = ~Temp, name = "MRC1", line = list(color = "red")) %>%
  add_lines(data = df_mrc, x = ~TIMESTAMP, y = ~Temp2, name = "MRC2", line = list(color = "darkred")) %>%
  add_lines(data = df_sat, x = ~valid_time, y = ~temp, name = "SAT", line = list(color = "purple")) %>%
  layout(yaxis = list(title = "Temperature °C"))

#Solar
plot_ly() %>%
  add_lines(data = df_meter_15min, x = ~Timestamps, y = ~Solar, name = "METER", line = list(color = "blue")) %>%
  add_lines(data = df_mrc, x = ~TIMESTAMP, y = ~Solar, name = "MRC1", line = list(color = "red")) %>%
  add_lines(data = df_mrc, x = ~TIMESTAMP, y = ~Solar2, name = "MRC2", line = list(color = "darkred")) %>%
  layout(yaxis = list(title = "Solar Radiation W/m^2"))

#WindSpeed
plot_ly() %>%
  add_lines(data = df_meter_15min, x = ~Timestamps, y = ~WindSpeed, name = "METER", line = list(color = "blue")) %>%
  add_lines(data = df_mrc, x = ~TIMESTAMP, y = ~WindSpeed, name = "MRC", line = list(color = "red")) %>%
  add_lines(data = df_sat, x = ~valid_time, y = ~wind_speed, name = "SAT", line = list(color = "purple")) %>%
  layout(yaxis = list(title = "Wind Speed m/s"))


#WindDir
plot_ly() %>%
  add_lines(data = df_meter_15min, x = ~Timestamps, y = ~WindDir, name = "METER", line = list(color = "blue")) %>%
  add_lines(data = df_mrc, x = ~TIMESTAMP, y = ~WindDir, name = "MRC", line = list(color = "red")) %>%
  add_lines(data = df_sat, x = ~valid_time, y = ~wind_direction, name = "SAT", line = list(color = "purple")) %>%
  layout(yaxis = list(title = "Wind Direction"))

```


```{r weather1, include = FALSE}
# library(dplyr)
# library(lubridate)
# library(zoo)
# library(tidyr)

# Save the filtered data frame to a CSV file
#filtered_df <- df_meter[, c("Timestamps", "Temp")]
#names(filtered_df) <- c("local_timestamp", "temp_c")
#write.csv(filtered_df, "MBRP_temp.csv", row.names = FALSE)

# Merge the dataframes, favoring df_meter in case of duplicate timestamps
# merged_df <- full_join(
#   df_mrc %>% select(TIMESTAMP, Temp2),
#   df_meter %>% select(Timestamps, MaxTemp),
#   by = c("TIMESTAMP" = "Timestamps")
# ) %>%
#   mutate(
#     Temp = coalesce(MaxTemp, Temp2)  # Favor MaxTemp from df_meter
#   )
#
# # Create a sequence of timestamps at 5-minute intervals
# time_seq <- seq(
#   from = min(merged_df$TIMESTAMP, na.rm = TRUE),
#   to = max(merged_df$TIMESTAMP, na.rm = TRUE),
#   by = "5 mins"
# )
#
# # Fill missing values only if the gap is smaller than 20 minutes
# filled_df <- merged_df %>%
#   arrange(TIMESTAMP) %>%
#   complete(TIMESTAMP = time_seq) %>%
#   mutate(
#     Temp2 = ifelse(
#       is.na(Temp) & !is.na(lag(Temp)) & !is.na(lead(Temp)) &
#       (difftime(lead(TIMESTAMP), TIMESTAMP, units = "mins") <= 20),
#       zoo::na.locf(Temp, na.rm = FALSE),
#       Temp
#     )
#   ) %>%
#   select(TIMESTAMP, Temp)
#
# names(filled_df) <- c("timestamp","max_temp_c")
# # View the filled dataframe
# print(filled_df)
# write.csv(filled_df, "MBRP_temp_both.csv", row.names = FALSE)
```


